// Code generated by swaggo/swag — peut être regénéré avec : swag init

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "PicoSum API",
        "description": "API de calcul de somme pour la POC PicoSum",
        "version": "1.0"
    },
    "host": "localhost:8081",
    "basePath": "/",
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "paths": {
        "/sum": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Calcule A + B. Les deux valeurs doivent être des entiers entre 0 et 10.",
                "produces": ["application/json"],
                "tags": ["calcul"],
                "summary": "Calcule la somme de deux entiers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Premier entier (0-10)",
                        "name": "a",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Second entier (0-10)",
                        "name": "b",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Résultat de la somme",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "sum": {"type": "integer"}
                            }
                        }
                    },
                    "400": {
                        "description": "Paramètre invalide",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {"type": "string"}
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {"type": "string"}
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo contient les métadonnées Swagger exportées.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PicoSum API",
	Description:      "API de calcul de somme pour la POC PicoSum",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
